version: "3"

services:
  db:
    image: mysql:latest
    container_name: local-mysql-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_forum
    volumes:
      - /Users/abimana/go/2024/mysql_data:/var/lib/mysql
